// SAMPLE members for demo mode only. These people are fictitious and are never used once Supabase is configured.
window.KIK_DEMO_MEMBERS = [
  ["Aarav Mehta", "Mehta Polymers", "Manufacturing & Industrial", "Plastics & Packaging", "Vatva", "Ahmedabad", "Gujarat", "India", 22.9637, 72.6337],
  ["Nisha Patel", "Patel & Co. Chartered Accountants", "Finance, Tax & Legal", "Chartered Accountant", "Navrangpura", "Ahmedabad", "Gujarat", "India", 23.0365, 72.5611],
  ["Kunal Shah", "Shah Diamonds", "Textiles, Apparel & Jewellery", "Diamonds", "Varachha", "Surat", "Gujarat", "India", 21.2094, 72.8558],
  ["Priya Desai", "Desai Textiles", "Textiles, Apparel & Jewellery", "Textile Manufacturing", "Ring Road", "Surat", "Gujarat", "India", 21.1959, 72.8302],
  ["Rohan Joshi", "BlueShift Labs", "Technology & IT", "Software & SaaS", "GIFT City", "Gandhinagar", "Gujarat", "India", 23.1603, 72.6839],
  ["Meera Iyer", "Iyer Legal", "Finance, Tax & Legal", "Lawyer / Advocate", "Fort", "Mumbai", "Maharashtra", "India", 18.9340, 72.8356],
  ["Vikram Rao", "Rao Realty", "Real Estate & Construction", "Developer / Builder", "Andheri", "Mumbai", "Maharashtra", "India", 19.1197, 72.8468],
  ["Ananya Gupta", "Northwind Exports", "Trading, Import & Export", "Export", "Nehru Place", "New Delhi", "Delhi", "India", 28.5494, 77.2519],
  ["Arjun Nair", "Kerala Spice Co.", "Agriculture & Agri-business", "Agri Trading", "Ernakulam", "Kochi", "Kerala", "India", 9.9816, 76.2999],
  ["Sneha Reddy", "Reddy Diagnostics", "Chemicals, Pharma & Healthcare", "Diagnostics & Labs", "Jubilee Hills", "Hyderabad", "Telangana", "India", 17.4326, 78.4071],
  ["Harsh Vora", "Vora Chem", "Chemicals, Pharma & Healthcare", "Chemicals & Dyes", "GIDC", "Vapi", "Gujarat", "India", 20.3712, 72.9051],
  ["Ishaan Kapoor", "Kapoor Solar", "Energy & Infrastructure", "Solar & Renewables", "Koramangala", "Bengaluru", "Karnataka", "India", 12.9352, 77.6245],
  ["Dhruv Thakkar", "Thakkar Logistics", "Logistics & Transport", "Freight & Shipping", "Gandhidham", "Kutch", "Gujarat", "India", 23.0753, 70.1337],
  ["Riya Sheth", "Sheth Advisory", "Consulting & Professional Services", "Advisory & M&A", "Alkapuri", "Vadodara", "Gujarat", "India", 22.3106, 73.1662],
  ["Karan Bhatt", "Bhatt Hospitality", "Hospitality, Food & Travel", "Hotels & Resorts", "Racecourse", "Rajkot", "Gujarat", "India", 22.3004, 70.7916],
  ["Sanjay Parikh", "Parikh Trading LLC", "Trading, Import & Export", "Import", "Deira", "Dubai", "Dubai", "United Arab Emirates", 25.2710, 55.3075],
  ["Hetal Amin", "Amin Gold", "Textiles, Apparel & Jewellery", "Gold & Jewellery", "Gold Souk", "Dubai", "Dubai", "United Arab Emirates", 25.2697, 55.2962],
  ["Raj Malhotra", "Malhotra Capital", "Finance, Tax & Legal", "Wealth & Investments", "Canary Wharf", "London", "England", "United Kingdom", 51.5054, -0.0235],
  ["Pooja Shah", "Wembley Foods", "Hospitality, Food & Travel", "Restaurants & Catering", "Wembley", "London", "England", "United Kingdom", 51.5588, -0.2817],
  ["Amit Trivedi", "Trivedi Motors", "Automobile", "Dealership", "Edison", "Edison", "New Jersey", "United States", 40.5187, -74.4121],
  ["Neel Doshi", "Doshi AI", "Technology & IT", "AI & Data", "Sunnyvale", "Sunnyvale", "California", "United States", 37.3688, -122.0363],
  ["Kavya Menon", "Menon Health", "Chemicals, Pharma & Healthcare", "Doctor / Specialist", "Brampton", "Brampton", "Ontario", "Canada", 43.7315, -79.7624],
  ["Yash Chokshi", "Chokshi Imports", "Trading, Import & Export", "Wholesale & Distribution", "Harris Park", "Sydney", "New South Wales", "Australia", -33.8193, 151.0078],
  ["Ritu Sanghvi", "Sanghvi Events", "Media, Marketing & Events", "Events & Weddings", "Little India", "Singapore", "Singapore", "Singapore", 1.3066, 103.8518],
  ["Manav Jain", "Jain Ventures", "Consulting & Professional Services", "Management Consulting", "Westlands", "Nairobi", "Nairobi", "Kenya", -1.2676, 36.8108],
  ["Tanvi Modi", "Modi EduTech", "Education & Training", "Coaching & EdTech", "Kothrud", "Pune", "Maharashtra", "India", 18.5074, 73.8077],
].map(([full_name, business_name, category, subcategory, locality, city, state, country, lat, lng], i) => ({
  id: "demo-" + i, full_name, business_name, category, subcategory, locality, city, state, country, lat, lng,
  place_label: [locality, city, state, country].filter((v, j, a) => v && a.indexOf(v) === j).join(", "),
  phone: "+9199000" + String(10000 + i).slice(-5), whatsapp: "+9199000" + String(10000 + i).slice(-5),
  email: full_name.split(" ")[0].toLowerCase() + "@example.com", sample: true,
}));
