"""Regenerate supabase/categories_seed.sql from js/categories.js (single source of truth)."""
import json, pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "js" / "categories.js").read_text()
data = json.loads(src[src.index("{"): src.rindex("}") + 1])

q = lambda s: "'" + s.replace("'", "''") + "'"
rows = [f"  ({q(c)}, {q(s)})" for c, subs in data.items() for s in subs]
sql = (
    "-- GENERATED by tools/gen_category_sql.py — do not edit by hand.\n"
    "delete from public.business_categories\n"
    " where (category, subcategory) not in (select category, subcategory from public.members);\n"
    "insert into public.business_categories (category, subcategory) values\n"
    + ",\n".join(rows)
    + "\non conflict do nothing;\n"
)
(root / "supabase" / "categories_seed.sql").write_text(sql)
print(f"Wrote {len(rows)} category rows")
